[Icon Theme]
Name=Gapr
Comment=Gapr icon theme (based on breeze icon theme).

Directories=breeze/16,breeze/22,breeze/24,breeze/32,breeze/64,16,32,64,scalable

[breeze/16]
Size=16
Type=Threshold

[breeze/22]
Size=22
Type=Threshold

[breeze/24]
Size=24
Type=Threshold

[breeze/32]
Size=32
Type=Threshold

[breeze/64]
Size=64
Type=Threshold

[16]
Size=16
Type=Threshold

[32]
Size=32
Type=Threshold

[64]
Size=64
Type=Threshold

[scalable]
MinSize=64
Size=128
MaxSize=256
Type=Scalable

