/android/
/build/
/build-*/

/.cache/
/.git/

/.flatpak-builder/
/packaging/Containerfile
/packaging/Containerfile.containerignore

/subprojects/*/
!/subprojects/*.wrap
!/subprojects/packagefiles/

/confdir/
/nodist/

